apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: NTgxZTk3M2ViMDcxMjcxMjg3OWMyMTBhMTFjOTkyODk3ZGY3MTljNTEyYmM3ZTBjMGQ0N2RmYzI5MDAwZTA4MDg2YjllZDQyZmFmMzhjOGM2ZDMyMjE4YTI2NzcyY2JhZGFlZmRlM2E2NGEzMTU3MjFiY2YxNTkxZTY5ZTM3ZDc=