apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-helper-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-helper-frontend
  template:
    metadata:
      labels:
        app: file-helper-frontend
    spec:
      containers:
        - name: file-helper-frontend
          image: australia-southeast1-docker.pkg.dev/sit323-24t1-butler-d014e9d/docker-repository/file-helper-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config
              name: config-files
      volumes:
        - configMap:
            name: uris
            defaultMode: 420
            optional: true
          name: config-files