apiVersion: v1
kind: ConfigMap
metadata:
  name: uris
data:
  MONGO_URI: "mongodb:27017/file-helper-cloud"
  appConfig.js: |
    window.appConfig = {
        USER_SERVICE_API_URI:       "http://34.128.139.44/api",
        PDF_SERVICE_API_URI:        "http://34.128.139.44/api",
        PDF_SERVICE_SOCKET_IO_URI:  "http://34.128.139.44/",
        PDF_SERVICE_SOCKET_IO_PATH: "/api/pdf/socket.io"
    };