apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-service-app
  template:
    metadata:
      labels:
        app: calculator-service-app
    spec:
      containers:
        - name: calculator-service-app
          image: sicsixdkn/calculator-service
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: calculator-service-app